export const FETCH_RENTALS_SUCCESS = "FETCH_RENTALS_SUCCESS";
export const FETCH_RENTAL_BY_ID_SUCCESS = "FETCH_RENTAL_BY_ID_SUCCESS";
export const FETCH_RENTAL_BY_ID_INIT = "FETCH_RENTAL_BY_ID_INIT";

export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOG_OUT = "LOG_OUT";
